#!/bin/bash
script_dir="`dirname "$0"`"
script_dir="`cd "$script_dir" ; pwd`"
cd "$script_dir"
mkdir -p out
rm book.html out/book.html
./genshify book.genshi.html > book.html
lilypond-book --output out/ book.html
